export default {
  FLAG_UP: 'FLAG_UP',
  FLAG_DOWN: 'FLAG_DOWN',
  FLAG_STOP: 'FLAG_STOP',
  RECEIVE_DEVICES: 'RECEIVE_DEVICES',
  REQUEST_DEVICES: 'REQUEST_DEVICES',
  ADD_DEVICE: 'ADD_DEVICE',
  REMOVE_DEVICE: 'REMOVE_DEVICE',
};
